### PR TITLE
Fix WebSockets

### PR DESCRIPTION
**Pull request by mmomjian**
A commit from the end of 2022 seems to have broken websocket support over HTTPS. This commit allows the project to work behind a Nginx HTTPS reverse proxy. For reference, here are my NGINX proxy instructions. The http_version 1.1 is needed for web sockets to work. 
```
location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        proxy_pass http://host:port/; }

```

### CODE REVIEW

**Comment by mmomjian** [comment]
Closes #8

**Review by seansegal — APPROVED** [review]
Thanks will try this

**Comment by seansegal** [comment]
@mmomjian I tried merging this PR (reverting the changes from earlier commits) and I still face the same issue. I haven't been able to have time to setup the nginx proxy in Heroku though likely explains the issue. Were you able to test on your end that this fixes the issue in #8 ? Thanks for your help!

**Comment by mmomjian** [comment]
@seansegal  I just did a fresh pull and build of the master branch and can confirm that it still works with the previously provided nginx settings. Let me know if you need any more help.

**Pull request merged**
